language: python
python:
- '2.7'
script:
- sudo apt-get install python-dev -y
- cd $TRAVIS_BUILD_DIR
- git clean -fXd
- pip install -r requirements.txt -t .
- rm -rf numpy boto*
- ls | grep dist-info | xargs rm -rf
- sed -i 's/StringIO/BytesIO/g' flask_ask/core.py
- rm flask_ask/core.pyc
- zip -r9 ~/Release.zip . -x \*.git\*
- mkdir dist
- mv ~/Release.zip dist/
before_deploy:
- git config --local user.name "m0ngr31"
- git config --local user.email "joe@ipson.me"
- git tag "$(date +'%m.%d.%Y')-$(git log --format=%h -1)"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: q0MyzY0Fq07KBnpqBCmzAj/g43l59wod12+60S1ZMPYqNfEsPkhLH/pFFbc0y8k/aaovOky9Pp/GyRQlezGIJmJU6F5kzVYMgoZcusvRoGbIh2uCREk/uJ4Io7SlqepGr2f2LS7Q32Gii/agXnA2x1P1TKlQHUUd6PDPHBFf/MV8MENwtT5shbgkpfZp8IAaFcAQGIiGMELhxqCESzMelGt5//MY+P30MoLBI3wrmmMs8kfci5WI6vBltmkmJHdVS70JvuVTepRApJhiOD3vpm/rbhXZ20E/4EAhNVHhDX3Zafkw1zprnLRsQiwYgIIrykEuW9cc0mcaaIifOfBZF5QW1b6e0mALj32qBw1KXhFEJ77e4sEt+VQsiFQbzPQrGOTdxIBupeOqmGtXrXHi8q5yVv8f4QbVbWutgyVMEMGW+rIUGClW/yX9I9l3R7TB7Ygdsez7JYgtXq2BpxBDCHFAsZdUL8sMm+LY8kpgCU8hXYkUZFVA5m7MaAJrO25Tk5hzPHkEWt9FnrXTqCvUXPVDSzm/NKd+Bx54AXa2gGeKefY8ylvrXfotJF++FvhANgyNVR78Rnra3OkDIwAZyCAFAEn+BANOp0scGEHkTS9bd6+IVzRo5/IedouXqsekDopKIqcC/nhz+hCplXgk92cNRVXra/aisZzWfWk4R5s=
  file: $TRAVIS_BUILD_DIR/dist/Release.zip
  on:
    repo: m0ngr31/koko
